version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "samdemostack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-dcrze8n5ompk"
s3_prefix = "samdemostack"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true
