# https://www.youtube.com/watch?v=psjz6rwzMdk
# venv pre-commit install
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
        name: Ensure that code don't have trailing whitespace
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        args: [--safe]

  - repo: https://github.com/PyCQA/flake8
    rev: 8.6.1
    hooks:
      - id: flake8