[tool.ruff]
# https://www.youtube.com/watch?v=bcAqceZkZRQ

# ruff linter
# ruff check test.py
# ruff check test.py --fix

# settings.json
#   "[python]": {
#     "editor.formatOnType": false,
#     "editor.formatOnSave": false,
#     "editor.defaultFormatter": "charliermarsh.ruff",
#     "editor.codeActionsOnSave": {
#       "source.fixAll": false,
#       "source.organizeImports": false
#     }
#   },

# extend-select = ["C4", "SIM", "TCH"]
# ignore = []
# show-fixes = true
# target-version = "py312"

# exclude = [
#   ".ruff_cache",
#   ".git",
#   ".venv",
#   "venv",
#   "build",
#   "dist"
# ]

#per-file-ignores = {}

# Same as Black
# line-length = 88

# [tool.ruff.isort]
