#https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app"

[default.build.parameters]
cached = false
parallel = false

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true

[default.sync.parameters]
watch = false

[default.local_start_api.parameters]
warm_containers = "EAGER"

[prod]
[prod.sync]
[prod.sync.parameters]
watch = false

#s3_bucket = "aws-samsourcebucket-sbZze8n5ompk"
#s3_prefix = "samstack1"
#region = "eu-west-1"
#image_repositories = []
#disable_rollback = false