AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: SAM template

Globals:
  Function:
    Timeout: 30
    MemorySize: 1769
    Runtime: python3.12

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      MemorySize: 1769
      Timeout: 60
      CodeUri: ./lambda_function/
      Policies:
        - SQSPollerPolicy:
            QueueName: !GetAtt SampleQueue.QueueName
      Events:
        Batch:
          Type: SQS
          Properties:
            Queue: !GetAtt SampleQueue.Arn
            FunctionResponseTypes:
              - ReportBatchItemFailures

  SampleQueue:
    Type: AWS::SQS::Queue
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      VisibilityTimeout: 30 #Fn timeout*6, 12 hours max
      MessageRetentionPeriod: 1209600 #14 days
      # FifoQueue: false
      # MaximumMessageSize: 262144
      # BatchSize: 1
      # DelaySeconds: 0
      # ReceiveMessageWaitTimeSeconds: 0
      # ContentBasedDeduplication: false
      # SqsManagedSseEnabled: true
      # KmsMasterKeyId: alias/aws/sqs
      # KmsDataKeyReusePeriodSeconds: 300
      RedrivePolicy:
        maxReceiveCount: 2
        deadLetterTargetArn: !GetAtt SampleDLQ.Arn
  
  SampleSNSTopic:
    Type: AWS::SNS::Topic
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      # FifoTopic: False
      Subscription:
        - Endpoint: !GetAtt SampleQueue.Arn
          Protocol: sqs
        - Endpoint: gtopcu@gmail.com
          Protocol: email
        - Endpoint: XXXXXXXXXXXXXXXX
          Protocol: sms
        - Endpoint: url
          Protocol: http
      

      