AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Simple HTTP API to Lambda function using python3.12

Resources:
  # Lambda function
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: apigwhttp_handler.handler
      CodeUri: lambdas/
      Runtime: python3.12
      Description: API handler function
      Timeout: 28
      MemorySize: 128
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            #ApiId: !Ref HttpApi
            Path: /testPath
            Method: ANY #GET
          #DefinitionBody:
          #  openapi: '3.0.3'
          #  info: {}

Outputs:
  HttpApiEndpoint:
    Value: !Sub 'https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com'

