AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: AWS SAM template for Lambda writing to DynamoDB

Resources:
  MyLambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      MemorySize: 1769
      Timeout: 60
      CodeUri: ./lambda_function/
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref MyDynamoDBTable

  MyDynamoDBTable:
    Type: 'AWS::DynamoDB::Table'
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      TableName: MyTable
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SortKey
          AttributeType: N
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SortKey
          KeyType: RANGE