default_stages: [commit]
fail_fast: true

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-toml

- repo: https://github.com/ambv/black
  rev: 22.3.0
  hooks:
  - id: black
    language_version: python3.8

- repo: https://github.com/timothycrosley/isort
  rev: 5.10.1
  hooks:
    - id: isort

- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
    - id: flake8
      additional_dependencies: [ flake8-isort ]
