name: Dispatch Event Workflow

on:
  repository_dispatch:
    types: [trigger-workflow-event]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Checkout Repo under custom folder named "component-templates"
        uses: actions/checkout@v2
        with:
          repository: xxx/component-templates
          path: "component-templates"

      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
          architecture: "x64"
        env:
          AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache

      - name: Install dependencies
        env:
          PIP_EXTRA_INDEX_URL: git+https://${{ secrets.GH_USERNAME }}:${{ secrets.GH_PAT }}@github.com/xxx/api-common.git@${{ env.CURRENT_BRANCH }}
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements/requirements.development.txt ]; then pip install -r requirements/requirements.development.txt; fi
      
      - name: Setup Django environment and run main.py
        env:
          DJANGO_SETTINGS_MODULE: djangoproject.settings
          PYTHONPATH: ${{ github.workspace }}/xxx:$PYTHONPATH
        run: |
          python component-templates/main.py

      - name: Install Testing and Linting Packages
        run: |
          echo "APP_ENV=test" >> $GITHUB_ENV
          if [ -f requirements/requirements.build.txt ]; then pip install -r requirements/requirements.build.txt; fi
      
      - name: Lint with flake8
        run: |
          flake8 --config=.flake8 .
      
      - name: Lint with Pylint
        run: |
          pylint --rcfile=.pylintrc . --django-settings-module=djangoproject.settings .
      
      - name: Test with pytest
        run: |
          python -m coverage run -m pytest