
# https://www.youtube.com/watch?v=bcAqceZkZRQ

# ruff check test.py
# ruff check test.py --fix

VSCode
settings.json
  "[python]": {
      "editor.formatOnType": false,
      "editor.formatOnSave": false,
      "editor.defaultFormatter": "charliermarsh.ruff",
      "editor.codeActionsOnSave": {
        "source.fixAll": "false",
        "source.organizeImports": "false",
      }
  }

# ruff.toml

# Assume Python 3.13
target-version = "py313"

# Enable pycodestyle (`E`) and Pyflakes (`F`) codes by default.
select = ["E", "F", "W", "I", "N", "B", "C4", "SIM", "ERA", "PL", "RUF"]

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]

# Same as Black.
line-length = 88

[lint]

# Ignore commented out code
ignore = ["ERA001"]

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[lint.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 10

[lint.per-file-ignores]
# Ignore `F401` (unused imports) in all `__init__.py` files
"__init__.py" = ["F401"]
# Ignore `E402` (import violations) in all `tests/` directories
"tests/*" = ["E402"]

[format]
# Like Black, use double quotes for strings.
quote-style = "double"
# Like Black, indent with spaces, rather than tabs.
indent-style = "space"
# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false
# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"