version = 0.1

[default.global.parameters]
stack_name = "FastAPISAMSample" 

[default.deploy]
[default.deploy.parameters]
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
s3_prefix = "fastapi-sample" 
region = "eu-east-1" 