version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "samstack"
s3_bucket = "aws-samsourcebucket-dcrze8n5ompk"
s3_prefix = "samstack"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = false
