
from setuptools import setup, find_packages

setup(
    name="calculator_package",
    version="0.0.1",
    description="calculator_package",
    long_description="calculator_package",
    author="hukanege",
    author_email="XXXXXXXXXXXXXXXXXXXXX",
    url="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    install_requires=[],
    packages=find_packages(),
)

# python setup.py sdist bdist_wheel
# twine upload --repository pypi dist/*

# def main() -> None:
    # XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    # XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    # XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    # XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    # XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    # XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    # XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
