https://www.youtube.com/watch?v=xhg1dJHLqSM
https://pre-commit.com/
https://docs.astral.sh/uv/
https://docs.astral.sh/uv/guides/integration/pre-commit/
https://github.com/astral-sh/ruff-pre-commit

requirements.txt -> pre-commit
.pre-commit-config.yaml -> .pre-commit-hooks.yaml

pre-commit.com
pip install pre-commit
pre-commit --version

pre-commit install
pre-commit installed at .git/hooks/pre-commit

pre-commit run --all-files

repos:
- repo: https://github.com/astral-sh/uv-pre-commit
  # uv version.
  rev: 0.5.5
  hooks:
    # Compile requirements
    - id: pip-compile
      args: [requirements.in, -o, requirements.txt]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.8.1
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format

- repo: local
  hooks: 
    - id: pytest
      name: pytest
      entry: ./ ./venv/bin/pytest tests
      language: python
      types: [python]
      pass_filenames: false
      always_run: true
      verbose: true
      stages: [commit]
      log_file: .pre-commit-pytest.log
      require_serial: true

# - repo: local
#   hooks: 
#     - id: python-lint
#       name: python-lint
#       entry: python-lint
#       language: python
#       types: [python]
#       pass_filenames: false
#       always_run: true
#       verbose: true
#       stages: [commit]
#       log_file: .pre-commit-python-lint.log
#       require_serial: true