
https://devtron.ai/blog/cmd-and-entrypoint-differences/

docker pull ubuntu
# docker run -it ubuntu bash

# --------------------------------------------------------------------

FROM ubuntu
CMD ["echo", "Hello World"]

FROM ubuntu
ENTRYPOINT ["echo", "Hello World"]

docker build -t myimage .
docker run myimage

docker run myimage echo "message changed"
docker run myimage printenv

# --------------------------------------------------------------------

FROM ubuntu:12.04

ENV DEBIAN_FRONTEND=noninteractive

# Install dependencies
RUN apt update -y
RUN apt install -y apache2

# Install apache and write hello world message
RUN echo "Hello Cloud Gurus!!!! This web page is running in a Docker container!" > /var/www/index.html

# Configure apache
RUN a2enmod rewrite
RUN chown -R www-data:www-data /var/www
ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_LOG_DIR /var/log/apache2

EXPOSE 8080
CMD ["/usr/sbin/apache2", "-D",  "FOREGROUND"]