

# Poetry:
FROM python:3.13-slim 
WORKDIR /app
COPY ./pyproject.toml ./poetry.lock* /app/
RUN pip install --no-cache-dir poetry
RUN poetry export -f requirements.txt --output requirements.txt --without-hashes
RUN pip install --no-cache-dir -r requirements.txt
CMD ["python", "app.py"]

# --------------------------------------------------------------------------------------------------------------

# https://medium.com/@anil.razzu/accessing-packages-of-aws-codeartifact-from-dockerfile-1452fe2d6261

FROM python:3.13-slim-buster
ENV POETRY_VIRTUALENVS_CREATE=false \
    POETRY_VERSION=1.2.2 \
    PATH="/root/.local/bin:$PATH"
WORKDIR /opt
ARG TOKEN="token"
COPY pyproject.toml ./pyproject.toml
RUN apt update -y 
RUN apt install -y curl && apt install -y curl && \
            pip install --upgrade poetry
            # curl -sSL 'https://install.python-poetry.org' | python - && poetry --version
RUN poetry config http-basic.repository_name aws $TOKEN && poetry install
COPY ./dob_calculator/ /opt/dob_calculator/
ENTRYPOINT ["python", "-m", "dob_calculator.calculator"]

# pull packages 
# poetry update

# build packages
# poetry build 

# push packages
# poetry publish -r dob_push