---
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  # Create a Launch Template with the desired instance configuration
  LaunchTemplate:
    Type: 'AWS::EC2::LaunchTemplate'
    Properties:
      LaunchTemplateData:
        ImageId: ami-0c94855ba95c71c99
        InstanceType: t2.micro
        SecurityGroupIds:
          - sg-1234567890abcdef0 # Replace with your security group ID
        UserData: !Base64 |
          #!/bin/bash
          echo "Hello from Auto Scaling Group" > /var/www/html/index.html
  # Create an Auto Scaling Group that uses the Launch Template
  AutoScalingGroup:
    Type: 'AWS::AutoScaling::AutoScalingGroup'
    Properties:
      AutoScalingGroupName: 'MyAutoScalingGroup'
      MinSize: 2
      MaxSize: 5
      DesiredCapacity: 2
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      VPCZoneIdentifier:
        - subnet-1234567890abcdef0 # Replace with your subnet ID(s)
        - subnet-0123456789abcdef
      TargetGroupARNs:
        - 'arn:aws:elasticloadbalancing:us-east-1:123456789012:targetgroup/MyTargetGroup/1234567890abcdef' # Replace with your target group ARN
